name: GitHub Actions

on:
  push:
    branches: ["main"]
        # allow us to run workflow from ui
  workflow_dispatch:      

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build  
      - name: upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Change this to your target branch
          FOLDER: build  # Change this to your build directory

